# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: docker:19.03.8

# open docker daemon service, need --privileged premission
services:
- name: docker:19.03.8-dind
  # if you need use repository by http portcol, uncomment next line
  command: ["--insecure-registry=47.95.254.230:8080"]

variables:
  GIT_SSL_NO_VERIFY: "true"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  harbor: "harbor.belstardoc.com"
  namespace: "tms"
  appName: "tms_appserver"
  dev_deploy_account: "kubernet"
  dev_deploy_host: "192.168.20.62"

before_script:
  - docker login -u $dev_harbor_user -p $dev_harbor_passwd $harbor

stages:
  - test
  - build
  - deploy

dev_test:
  stage: test
  only:
    - /^dev-.*$/
  script:
    - echo "$dev_env" > .env
    - docker pull $harbor/$namespace/$appName:latest-test || true
    - docker build --cache-from $harbor/$namespace/$appName:latest-test -t $harbor/$namespace/$appName:$CI_COMMIT_REF_NAME-test -f Dockerfile.test .
    - docker run --rm -i $harbor/$namespace/$appName:$CI_COMMIT_REF_NAME-test ./node_modules/.bin/eslint .
    # - docker run --rm -i $harbor/tms/$appName:$CI_COMMIT_REF_NAME-test npm run test
    - docker tag $harbor/$namespace/$appName:$CI_COMMIT_REF_NAME-test $harbor/$namespace/$appName:latest-test
    - docker push $harbor/$namespace/$appName:$CI_COMMIT_REF_NAME-test
    - docker push $harbor/$namespace/$appName:latest-test

dev_build:
  stage: build
  only:
    - /^dev-.*$/
  script:
    - echo $dev_env > .env
    - docker pull $harbor/$namespace/$appName:latest || true
    - docker build --cache-from $harbor/$namespace/$appName:latest -t $harbor/$namespace/$appName:$CI_COMMIT_REF_NAME -f Dockerfile.build .
    - docker tag $harbor/$namespace/$appName:$CI_COMMIT_REF_NAME $harbor/$namespace/$appName:latest
    - docker push $harbor/$namespace/$appName:$CI_COMMIT_REF_NAME
    - docker push $harbor/$namespace/$appName:latest

dev_deploy:
  stage: deploy
  only:
    - /^dev-.*$/
    - /dev_deploy-.*$/
  script:
    # If need push to other repositories, uncommit follow line
    # - docker pull lab.yukifans.com/$appName:$CI_COMMIT_REF_NAME
    # - docker push lab.yukifans.com/$appName:$CI_COMMIT_REF_NAME
    # - docker pull lab.yukifans.com/$appName:latest
    # - docker push lab.yukifans.com/$appName:latest
    - apk add openssh
    - mkdir ~/.ssh && chmod 700 ~/.ssh
    - echo "$dev_ssh_private_key" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$dev_deploy" > tms_appserver.yaml
    - echo "$dev_config_map" > tms_appserver_config_map.yaml
    - sed -i -e "s/$harbor\/$namespace\/${appName}:latest/$harbor\/$namespace\/${appName}:${CI_COMMIT_REF_NAME}/g" tms_appserver.yaml
    - scp -o StrictHostKeyChecking=no tms_appserver_config_map.yaml $dev_deploy_account@$dev_deploy_host:~/TMS/tms_appserver_config_map.yaml
    - ssh -o StrictHostKeyChecking=no $dev_deploy_account@$dev_deploy_host "kubectl -f ~/TMS/tms_appserver_config_map.yaml apply"
    - scp -o StrictHostKeyChecking=no tms_appserver.yaml $dev_deploy_account@$dev_deploy_host:~/TMS/tms_appserver.yaml
    - ssh -o StrictHostKeyChecking=no $dev_deploy_account@$dev_deploy_host "kubectl -f ~/TMS/tms_appserver.yaml apply"
    - ssh -o StrictHostKeyChecking=no $dev_deploy_account@$dev_deploy_host "kubectl -n tms annotate deployment tms-appserver kubernetes.io/change-cause=\"image updated to $CI_COMMIT_REF_NAME. $CI_COMMIT_MESSAGE\""
    
